base/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

from django.shortcuts import redirect

def logout_required(view_func):
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated:
            # User is logged in, redirect to a different URL
            return redirect('home')  # Replace 'home' with the desired URL name
        return view_func(request, *args, **kwargs)
    return wrapper




urlpatterns = [
    path('',views.home,name="home"),
    # login View
    path('login/',views.loginPage,name="login"),
    # logout view
    path('logout/',views.logoutUser,name='logout'),
    # register page
    path('register',views.registerUser,name='register'),
    path('settings',views.newsettings,name='settings'),
    path('profile/<str:pk>/',views.userProfile,name='user-profile'),
    path('upload/',views.upload,name='upload-post'),
    path('discover/',views.suggestionFeed,name='suggestion-feed'),
    path('like-post/',views.like_post,name='like-post'),
    path('like-postt/',views.like_post_nonajax,name='like-post'),
    path('delete-post/<str:pk>',views.deletePost,name='delete-post'),
    path('comment-post/<str:pk>',views.postcomment,name='comment-post'),
    # path('ajax/',views.checkforajax,name='ajax'),
    path('notification/',views.notification,name='notification'),

    path('password_reset/', logout_required(auth_views.PasswordResetView.as_view(template_name="base_app/password_reset.html")), name='password_reset'),
    path('password_reset/done/', logout_required(auth_views.PasswordResetDoneView.as_view(template_name="base_app/password_reset_sent.html")), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', logout_required(auth_views.PasswordResetConfirmView.as_view(template_name="base_app/password_reset_form.html")), name='password_reset_confirm'),
    path('reset/done/', logout_required(auth_views.PasswordResetCompleteView.as_view(template_name="base_app/password_reset_done.html")), name='password_reset_complete'),
]

pexelens/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
import uuid

from PIL import Image
from io import BytesIO
from django.core.files import File

# Create your models here.

class Profile(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    id_user = models.IntegerField()
    follows = models.ManyToManyField("self",symmetrical=False,blank=True,related_name="Followed_by")
    bio = models.CharField(max_length=50,blank=True)
    profileimg=models.ImageField(upload_to='profile-images',default='blank-profile-picture.png')
    location = models.CharField(max_length=100,blank=True)

     # before saving the instance we’re reducing the image
    def save(self, *args, **kwargs):
        new_image = self.reduce_image_size(self.profileimg)
        self.profileimg = new_image
        super().save(*args, **kwargs)


    def reduce_image_size(self, profileimg):
        img = Image.open(profileimg)
        thumb_io = BytesIO()
        img.save(thumb_io, 'jpeg', quality=20)
        new_image = File(thumb_io, name=profileimg.name)
        return new_image

    def __str__(self):
        return self.user.username
    

    

class Post(models.Model):
    id= models.UUIDField(primary_key=True,default=uuid.uuid4)
    user = models.CharField(max_length=100)
    image = models.ImageField(upload_to='post_images')
    caption = models.TextField(blank=True)
    created_at =models.DateTimeField(auto_now_add=True)
    no_of_likes = models.IntegerField(default=0)
    no_of_comments =models.IntegerField(default=0)

     # before saving the instance we’re reducing the image
    def save(self, *args, **kwargs):
        new_image = self.reduce_image_size(self.image)
        self.image = new_image
        super().save(*args, **kwargs)


    def reduce_image_size(self, image):
        img = Image.open(image)
        thumb_io = BytesIO()
        img.save(thumb_io, 'jpeg', quality=30)
        new_image = File(thumb_io, name=image.name)
        return new_image

    def __str__(self):
        return self.caption

# model for like post
class LikePost(models.Model):
    post_id = models.CharField(max_length=500)
    username  = models.CharField(max_length=100)

    def __str__(self):
        return self.username
    
class CommentPost(models.Model):
    id= models.UUIDField(primary_key=True,default=uuid.uuid4)
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE) 
    user = models.CharField(max_length=30)
    body = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.body
    
class Notification(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='received_notifications')
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    liked_by = models.ForeignKey(User,on_delete=models.CASCADE, related_name='liked_notifications')
    seen = models.BooleanField(default=False)
    iscomment = models.BooleanField(default=False)
    comment_detail = models.ForeignKey(CommentPost,on_delete=models.CASCADE,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

base/forms.py
from django.forms import ModelForm
# from .models import
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile,Post
from django.shortcuts import redirect


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=20, required=True)
    last_name = forms.CharField(max_length=20, required=True)

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('email','first_name','last_name')

    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        # if User.objects.filter(email=email).exists():
            # raise forms.ValidationError("This email is already in use.")
        return email



class AccountForm(ModelForm):
    class Meta:
        model = Profile
        # fields = '__all__'
        exclude = ['user', 'id_user','follows']
        labels = {
            'profileimg': 'Profile Image'
        }

class UploadPostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['image','caption']

base/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from .models import Profile,Post,LikePost,CommentPost,Notification

from .forms import CustomUserCreationForm,UploadPostForm
from django.db.models import Q , Count 
import uuid , os







# login Page 
def loginPage(request):
    form = CustomUserCreationForm()
    page='login'
    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')
    
        try:
            user = User.objects.get(username=username)
            user = authenticate(request,username=username,password=password)
            if user is not None:
                login(request,user)
                return redirect('home')
            else:
                messages.error(request,'Credentials Invalid')
        except:
            messages.error(request,"User does not exist")
    context={'page':page,'form':form}
    # return render(request,'base/loginpage.html',context)
    return render(request,'newlogin.html',context)




# logout page
@login_required(login_url='login')
def logoutUser(request):
    logout(request)
    return redirect('home')



# Home Page View
@login_required(login_url='login')
def home(request):
    #get user
    user=request.user
    user_profile = Profile.objects.get(user=user)
    followed_users = user_profile.follows.all()
    followed_usernames = list(followed_users.values_list('user__username', flat=True))
    followed_usernames.append(user.username)
    q=request.GET.get('q') if request.GET.get('q') else ''
    sort_by = request.GET.get('sort_by')

    posts=Post.objects.filter(
         Q(user__in=followed_usernames) & (Q(user__icontains=q) | Q(caption__icontains=q) )).order_by('-created_at')
    
    if sort_by == 'popular':
        posts = posts.order_by('-no_of_likes')

    all_user = Profile.objects.all()
    
    liked_post_ids = LikePost.objects.filter(username=user.username).values_list('post_id', flat=True)
    liked_post_ids = [uuid.UUID(post_id) for post_id in liked_post_ids]  # Convert post IDs to UUID format



    context={'posts':posts,'user_profile':user_profile,'all_user':all_user,'liked_post_ids': liked_post_ids,}

    newUser = followed_users.count() == 0 and user_profile.Followed_by.count() == 0

    if newUser:
        context['is_new_user'] = True

    return render(request,'base_app/home.html',context)





# Discover Page view
@login_required(login_url='login')
def suggestionFeed(request):

    if request.method == 'POST':
        pass

    user_profile = Profile.objects.get(user=request.user)
    q=request.GET.get('q') if request.GET.get('q') else ''

    followed_profiles = user_profile.follows.all()
    users = [profile.user for profile in followed_profiles]
    all_users = Profile.objects.filter(Q(user__username__icontains=q)).exclude(user=request.user).exclude(user__in=users).annotate(num_followers=Count('Followed_by')).order_by('-num_followers')



    context = {"all_users":all_users,'user_profile':user_profile}
    return render(request,'base_app/suggestions.html',context)




@login_required(login_url='login')
def upload(request):
    form = UploadPostForm()
    user_profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        form = UploadPostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user.username


            post.save()
            return redirect('home')

    context = {'form': form, 'user_profile': user_profile}
    return render(request, 'base_app/upload.html', context)





@login_required(login_url='login')
def newsettings(request):
    user=request.user
    user_profile = Profile.objects.get(user=user)

    if 'name-form' in request.POST:
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.save()
        messages.success(request,"Name changed successfully !")
        return redirect('settings')
    

    if request.method == 'POST':
        user_profile.bio = request.POST.get('bio')
        user_profile.location = request.POST.get('location')

        if len(request.FILES) != 0:
            if len(user_profile.profileimg):
                os.remove(user_profile.profileimg.path)
            profileimg=request.FILES.get('profileimg')
            user_profile.profileimg = profileimg
        user_profile.save()
        messages.success(request,"Profile Updated !")

    
    context={'user_profile':user_profile,'user':user}
    return render(request,'base_app/edit-profile.html',context)







# Register Page
def registerUser(request):
    page='register'
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        
        if form.is_valid():
            user = form.save(commit=False)#to clean the data like username to all lowercase
            user.username=user.username.lower()
            email = form.cleaned_data.get('email')
            if User.objects.filter(email=email).exists():
                messages.error(request,'Email Taken')
                return redirect('register')
            # user.email = email
            user.save()

            #login the user
            login(request,user)


            #create a profile object for the new user
            uprofile = User.objects.get(username=user.username)
            new_profile = Profile.objects.create(user=uprofile,id_user=uprofile.id)
            new_profile.save()

            
            return redirect('settings') 
        else:
            #flash them that some error occured
            messages.error(request,'Something went wrong ! Try Again.')


    context={'form':form,'page':page}
    # return render(request,'base/loginpage.html',context)
    return render(request,'newlogin.html',context)

@login_required(login_url='login')
def userProfile(request,pk):
    user=User.objects.get(username=pk)
    user_profile =  Profile.objects.get(user=user)
    user_post = Post.objects.filter(user=pk)
    logged_user = Profile.objects.get(user=request.user)

    

    if request.method == 'POST' and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        # if 'follow' in request.POST:
        action = request.POST.get('action')
        if action == 'follow':
            logged_user.follows.add(user_profile)
            return JsonResponse({'status': 'success', 'message': 'Followed successfully'})
        # elif 'unfollow' in request.POST:
        elif action == 'unfollow':
            logged_user.follows.remove(user_profile)
            return JsonResponse({'status': 'success', 'message': 'Unfollowed successfully'})
    
    it_follows = logged_user.follows.filter(user=user).exists()
    #posts
    #posts_comments
    #hashtags
    context={'user':user,'user_profile':user_profile,'user_post':user_post,'it_follows':it_follows}
    return render(request,'base_app/profile.html',context)
    # return render(request,'base/custom_profile.html',context)










@login_required(login_url='login')
def like_post_nonajax(request):
    username = request.user.username
    post_id = request.GET.get('post_id')
    # post = Post.objects.get(id=pk)
    post = Post.objects.get(id=post_id)
    # post_id = post.id


    # if the post is liked by user or not
    like_filter = LikePost.objects.filter(post_id=post_id,username=username).first()
    if like_filter is None:
        new_like = LikePost.objects.create(post_id=post_id,username=username)
        new_like.save()
        post.no_of_likes += 1
        post.save()
        return redirect(request.META['HTTP_REFERER'])
    else:
        like_filter.delete()
        post.no_of_likes-= 1
        post.save()
        return redirect(request.META['HTTP_REFERER'])

@login_required(login_url='login')
def like_post(request):
    if request.method == 'POST' and request.headers.get('x-requested-with') == 'XMLHttpRequest':

        username = request.user.username
        post_id = request.POST.get('post_id')

        post = Post.objects.get(id=post_id)
        user_instance = User.objects.get(username = post.user)



        like_filter = LikePost.objects.filter(post_id=post_id, username=username).first()

        if like_filter is None:
            new_like = LikePost.objects.create(post_id=post_id, username=username)
            new_like.save()
            post.no_of_likes += 1
            post.save()
            new_notification = Notification.objects.create(user=user_instance, post=post, liked_by=request.user)
            new_notification.save()
            # return JsonResponse({'likes_count': post.no_of_likes})
        else:
            like_filter.delete()
            post.no_of_likes -= 1
            post.save()
            Notification.objects.filter(user=user_instance, post=post, liked_by= request.user).delete()


        notifications = request.user.received_notifications.filter(seen=False)
        count_unseen_notifications = notifications.count()
        return JsonResponse({'likes_count': post.no_of_likes,"count_unseen_notifications":count_unseen_notifications})
    else:
        return JsonResponse({'error': 'Invalid request'})









@login_required(login_url='/login')
def deletePost(request,pk):
    
    user_profile =  Profile.objects.get(user=request.user)
    post = Post.objects.get(id=pk)

    if request.user.username != post.user:
        return HttpResponse("You are not allowed here")

    if request.method == 'POST':
        if len(post.image):
            os.remove(post.image.path)
        post.delete()
        return redirect('/profile/' + str(post.user))
    context={'obj':post,'user-profile':user_profile}

base/templates/base_app/comment.html
{% extends 'main.html' %}
{% load static %}
{% load displayTimeCustom %}



{% block styles %}
<link rel="stylesheet" href="{% static 'base_app/styles/comments.css' %}">
{% endblock styles %}


    
    {% block title %}
    <title>View Post</title>
      
    {% endblock title %}
        

{% block nav %}
  {% include 'nav.html' %}
{% endblock nav %}



{% block content %}
  
<section class="comment-page">

<div class="comment-section">
  
  {% if post.user == request.user.username  %}
    
  
    
  <div class="close">
    <!-- <a  href="{% url 'delete-post' post.id %}"><i title="delete-post" class="bi bi-trash3-fill"></i></a> -->
    <!-- <i class="bi bi-x-circle-fill"></i> -->
    <i title="delete-post" class="bi bi-trash3-fill"></i>
  </div>
  {% endif %}
  <div class="comment-imagediv">
    <img src="{{post.image.url}}" alt="">
    
  </div>
  <div class="comment-action">
    

    {% if post.caption %}
    <div class="comment-username">
      {% else %}
      <div class="comment-username" style="height: 80px;">
      {% endif %}
    



      <div class="comment-username-profile">

        <div class="post-img ">
            <img src="{{post_owner.profileimg.url}}" alt="profile">
        </div>
        <div class="user-profile-comment">
          <a href="{% url 'user-profile' post.user %}">{{post.user}}</a>
          <span class="post-time">{{post.created_at|display_time_elapsed}}</span>
      </div>
      </div>
      
      {% if post.caption %}
        <p>{{post.caption}}</p>  
       {% endif %} 
    </div>


    {% if post.caption %}
    <div class="comment-comment-area">
    {% else %}
    <div class="comment-comment-area" style="height: 470px;">
    {% endif %}
      {% if comments %}
        
      
        
      {% for comment in comments  %}
        <div class="comments">
        <div class="comment-body">
          <div class="comment-user-img">
            <img src="{{post_owner.profileimg.url}}" alt="profile">
          </div>
          <a href="{% url 'user-profile' comment.user  %}">{{comment.user}}</a>
          <p>{{comment.body}}</p>

        </div>
        <p class="timesince">{{comment.created_at|display_time_elapsed}} </p>
        </div>
      {% endfor %}
        {% else %}
        <p class="comment-empty">No Comments</p>
      {% endif %}
    </div>

    <div class="comment-icons">
      <form action="{% url 'comment-post' post.id %}" method="GET">
      <input name="enter_comment" type="text" placeholder="Enter your comment">
      </form> 
      <a href="/like-postt?post_id={{post.id}}">{% if is_liked %}<i class="bi bi-heart-fill" style="color: red;"></i>{%else%}<i class="bi bi-suit-heart"></i>{% endif %}</a>
      </div>

    </div>
    </div>
</div>


<div class="delete-page">
  <form method="POST" action="{% url 'delete-post' post.id %}">
    {% csrf_token %}
    <p>Click to delete following post?</p>
        <input type="submit" value="Delete">
          <span>Cancel</span>
      </div>
  </form>
</div>


</section>
{% endblock content %}



{% block scripts %}
<script src="{% static 'base_app/js/comment.js' %}"></script>

{% endblock scripts %}

base/templates/base_app/edit-profile.html
{% extends 'main.html' %}

{% load static %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'base_app/styles/edit-profile.css' %}">
{% endblock styles %}
  
    
{% block title %}
    <title>Edit Profile</title>
{% endblock title %}
      
{% block nav %}
{% include 'nav.html' %}
{% endblock nav %}




{% block content %}


{% if messages %}
<div class="error-messages">
  {% for message in messages %}
  <div class="error-message">
    <p>{{ message }}</p>
    <button><i class="bi bi-x-circle-fill"></i></button>     
  </div>
  {% endfor %}
</div>
{% endif %}


  <section class="settings-page animate-in">
    <div class="settings-profileimg">
        <img src="{{user_profile.profileimg.url}}" alt="">
    </div>
    <span class="settings-profilename">{{user.first_name}} {{user.last_name}} <button>edit<i class="bi bi-pencil-fill"></i></button></span>

    <form id="settings-account-form"  action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
        <h2>Edit Profile</h2>

       
        
        <div class="signin-fields">
            <label for="Bio">Bio</label>
            <input type="text" name="bio" value="{{user_profile.bio}}"  maxlength="100" id="id_bio" >
        </div>
        
        <div class="signin-fields">
            <label for="Profile Image">Change Profile Image</label>
            <input type="file" name="profileimg" accept="image/*" id="id_profileimg">
        </div>
       
        
        <div class="signin-fields">
            <label for="Location">Location</label>
            <input type="text" name="location" value="{{user_profile.location}}" maxlength="100" id="id_location">
        </div>
        
        
        <a class="cancel-btn" href="/">Cancel</a>
        <input name="profile-form"  class="save-btn" type="submit" value="Save">
    </form>


    <form action="" id="editname-form" class="editname-form" method="POST">
      {% csrf_token %}

      <div class="signin-fields-name">

        <div class="signin-fields">
            <label for="first-name">First Name</label>
            <input id="first-name" name="first_name" type="text" placeholder="First name" value="{{user.first_name}}" required >
        </div>

        <div class="signin-fields">
            <label for="last-name">Last Name</label>
            <input id="last-name" name="last_name" type="text" placeholder="Last Name" value="{{user.last_name}}" required>
        </div>

    </div>
      <span class="cancel-btn">Cancel</span>
      <input name="name-form" class="save-btn" type="submit" value="Save">
    </form>
  </section>
{% endblock content %}



{% block scripts %}
<script src="{% static 'base_app/js/edit-profile.js' %}"></script>
  
{% endblock scripts %}
  

base/templates/base_app/home.html
{% extends 'main.html' %}
{% load static %}
{% load displayTimeCustom %}  

    {% block styles %}
    <link rel="stylesheet" href="{% static 'base_app/styles/home.css' %}">  
    {% endblock styles %}
      

    
    {% block title %}
    <title>PexeLens </title>   
    {% endblock title %}

    {% block nav %}
    {% include 'nav.html' %}
    {% endblock nav %}

    {% block content %}

    {% if is_new_user %}
    <div class="newuser-display animate-in">
      <p>Welcome to our platform !</p>
      <span>Click <a href="{% url 'suggestion-feed' %}">here</a>  to find and connect with people.</span>
    </div>
    {% else %}
      
    

    
<div class="error-messages">
  <div class="error-message">
    <p></p>
    <button><i class="bi bi-x-circle-fill"></i></button>     
  </div>
</div>
  

    <!-- main -->
    <main class="main-home animate-in" >
  <!--   main-post -->    

  <div class="feed">
    <h1>Feed</h1>
    <form method="GET" action="" class="feed-text">
      <input type="hidden" name="q" value="{{ request.GET.q }}">
      <button type="submit" name="sort_by" value="latest">Latest</button>
      <button type="submit" name="sort_by" value="popular">Popular</button>
    </form>
  </div>
<!--  Posts  -->
  <div class="main-posts">
      
<!--   Box1   -->
{% for post in posts   %}
    <div class="post-box">
      
      <a href="{% url 'comment-post' post.id %}"><img src="{{post.image.url}}" data-src="{{post.image.url}}" class="lazy-load"  alt=""></a>
      
      <div class="post-info">
      
        <div class="post-profile">
          <div class="post-img">

            {% for single_user in all_user  %}
              {% if single_user.user.username == post.user %}
              <img src="{{single_user.profileimg.url}}"  alt="profile">
              {% endif %}
                
            {% endfor %}
          </div>
          <a href="{% url 'user-profile' post.user %}"><h3>{{post.user}}</h3></a>
        </div>
                
        <div class="likes"> 
            
<!--           heart icon -->
  
          <button class="like-btn-home" data-post-id="{{ post.id }}" data-csrf="{{ csrf_token }}">
            
              
            {% if post.id in liked_post_ids %}
            <i class="bi bi-heart-fill" style="color: red;"></i>
            {% else %}
            <i class="bi bi-suit-heart" ></i>
            {% endif %}
            </button>
          <span class="like-count-home"  data-post-id="{{ post.id }}">{{post.no_of_likes}} </span> 

<!--           comment icon -->

          <button class="comment-button-home" ><i class="bi bi-chat"></i></button>
          <span class="comment-count-home" data-post-id="{{ post.id }}">{{post.no_of_comments}} </span>
          
        </div>
      </div>
      <div class="caption">
        <p>{{post.caption}}</p>
        <span class="post-time">{{post.created_at|display_time_elapsed}} ago</span>
      </div>

      <div class="post-box-comment">
        <p>Add Comment</p>
        <div class="comment-input-field">
          <input type="text" placeholder="enter comment">
          <button class="send-comment"  data-post-id="{{ post.id }}" data-csrf="{{ csrf_token }}" ><i class="bi bi-send-fill"></i></button>
          <button class="close-commentdiv"><i class="bi bi-x-circle-fill"></i></button>
        </div>
      </div>

      
    </div>
{% empty %}
    <div><p>No Match Found</p></div>
{% endfor %}

    



    
  </div>


    </main>

    <button id="scrollToTop" class="animate-in"><i class="bi bi-arrow-up-circle-fill"></i></button>
    {% endif %}
  {% endblock content %}

  {% block scripts %}

  <script src="{% static 'base_app/js/home.js' %}"></script>

  {% endblock scripts %}

base/templates/base_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="./styles/signin.css">
    <title>PexeLens - login</title>
</head>
<body>
    <nav>
        <div class="logo">
          <a href="./home.html">
            <h1>PIXE<span>L</span>ENS</h1>

          </a>
        </div>
    </nav>

    <div class="error-messages">
        <div class="error-message">
            <p>Usename doesnt exist</p>
            <button><i class="bi bi-x-circle-fill"></i></button></div>
    </div>
    
    <div class="signin-container">

        <div id="signin-page" class="card">
            
            <form id="signin-form" action="">
                <div class="signin-heading">
                    <h2>Sign in to your account</h2>
                </div>
                

                <div class="signin-fields">
                    <label for="username">Username</label>
                    <input id="username" type="text" placeholder="Enter your username">
                </div>

                <div class="signin-fields">
                    <label for="password">Password</label>
                    <input id="password" type="password" placeholder="Enter your password">
                </div>
                <a class="forgot-password-link" href="#">Forgot password? Click here to reset.</a>
                <button class="sign-button" type="">Sign in</button>
            </form>
            
            <span>Don't have an account?<button class="signup-link">Sign Up</button></span>
             
            
            
                <div class="wave">
                    <img src="./assests/Path.png" alt="">
                </div>
                <div class="wave">
                    <img src="./assests/Path 2.png" alt="">
                </div>


        </div>


        
  <div class="card" id="register-card">

    <form id="signin-form" action="">
        <div class="signin-heading">
            <h2>Register your Account</h2>
        </div>
        



        <div class="signin-fields">
            <label for="username">Username</label>
            <input id="username" type="text" placeholder="Enter your username">
        </div>

        <div class="signin-fields">
            <label for="email">Email</label>
            <input id="email" type="email" placeholder="Enter your email" required>
        </div>


        <div class="signin-fields-name">

        


        <div class="signin-fields">
            <label for="email">First Name</label>
            <input id="email" type="email" placeholder="Enter your email" required>
        </div>


        <div class="signin-fields">
            <label for="email">Last Name</label>
            <input id="email" type="email" placeholder="Enter your email" required>
        </div>

    </div>

        <div class="signin-fields">
            <label for="re-password">Password</label>
            <input id="re-password" type="password" placeholder="re-enter your password">
        </div>

        <div class="signin-fields">
            <label for="password">Confirm Password</label>
            <input id="password" type="password" placeholder="Re-enter your password">

        
        </div>

        
        <button class="sign-button" type="">Sign up</button>
    </form>
    
    <span>Already have an account?<button class="signin-link">Sign In</button></span>
     
    
    
        <div class="wave">
            <img src="./assests/Path.png" alt="">
        </div>
        <div class="wave">
            <img src="./assests/Path 2.png" alt="">
        </div>

  </div>



    </div>


    <script src="./js/signin.js"></script>
    </body>
</html>

base/templates/base_app/upload.html
{% extends 'main.html' %}
{% load static %}


{% block styles %}
<link rel="stylesheet" href="{% static 'base_app/styles/upload.css' %}">
{% endblock styles %}
  

    
    {% block title %}
    <title>Upload Page</title>
      
    {% endblock title %}
    

    {% block nav %}
    {% include 'nav.html' %}
    {% endblock nav %}


{% block content %}
  
    <section class="upload-page animate-in">
  
      <form id="upload-account-form"  action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Upload Post</h2>


        <div class="signin-fields">
          <label for="{{field.id_for_label}}">Select Photo</label>
          {{form.image}}
        </div>

        <div class="signin-fields">
          <label for="id_caption">Caption</label>
          {{form.caption}}
          <span id="charCount">75 characters remaining</span>
        </div>
          <a class="cancel-btn" href="/">Cancel</a>
          <input class="save-btn" type="submit" value="upload">
      </form>
    </section>
        
{% endblock content %} 
        


{% block scripts %}
<script src="{% static 'base_app/js/upload.js' %}"></script>
{% endblock scripts %}  
    